---
- name: Add go ppa
  apt_repository: repo=ppa:longsleep/golang-backports state=present
  become: yes

- name: install go
  apt:
    name: golang-go
    state: latest
    update_cache: yes
  become: yes

- name: create gopath
  file:
    path: ~/development/go
    state: directory

- name: add gopath variables to bash
  blockinfile:
    path: ~/.bashrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK - gopath"
    block: |
      GOPATH=~/development/go
