---
- name: create ssh keys dir
  file:
    path: ~/.ssh
    state: directory

- name: set timezone
  become: yes
  timezone:
    name: America/Sao_Paulo

- name: clone fzf repo
  git:
    repo: https://github.com/junegunn/fzf
    dest: ~/.fzf
  notify:
    - install fzf

- name: install ag silver search
  apt:
    name: silversearcher-ag
    state: latest
  become: yes

- name: install httpie
  apt:
    name: httpie
    state: latest
  become: yes

- name: install jq
  apt:
    name: jq
    state: latest
  become: yes

- name: install powerline fonts
  apt:
    name: fonts-powerline
    state: latest
  become: yes

- name: install firacode fonts
  apt:
    name: fonts-firacode
    state: latest
  become: yes

- name: install snapd
  apt:
    name: snapd
    state: latest
  become: yes

- name: install starship prompt
  shell: snap install starship
  become: yes

- name: add starship in bashrc
  blockinfile:
    path: ~/.bashrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK - starship"
    block: |
      eval "$(starship init bash)"

- name: install libpq-dev
  apt:
    name: libpq-dev
    state: latest
  become: yes

- name: install postgresql
  apt:
    name: postgresql
    state: latest
  become: yes

- name: install postgresql-contrib
  apt:
    name: postgresql-contrib
    state: latest
  become: yes

- name: DEBIAN | Set URL to download bins
  set_fact:
    debian_url: "https://github.com/sharkdp/bat/releases/download/v0.12.1/bat_0.12.1_amd64.deb"

- name: DEBIAN | Install deb from github
  become: true
  apt:
    deb: "{{ debian_url }}"
