---
- name: install packages required for building python
  become: yes
  apt:
    pkg:
      - build-essential
      - curl
      - git
      - libffi-dev
      - liblzma-dev
      - libncurses5-dev
      - libncursesw5-dev
      - libreadline-dev
      - libsqlite3-dev
      - libssl-dev
      - libbz2-dev
      - llvm
      - make
      - python-openssl
      - tk-dev
      - wget
      - xz-utils
      - zlib1g-dev

- name: clone pyenv
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: ~/.pyenv

- name: add pyenv variables to bash
  blockinfile:
    path: ~/.bashrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK - pyenv"
    block: |
      export PYENV_ROOT="$HOME/.pyenv"
      export PATH="$PYENV_ROOT/bin:$PATH" 
      eval "$(pyenv init -)"
