---
- name: install pip3
  apt:
    name: python3-pip
    state: latest

- name: install pip
  apt:
    name: python-pip
    state: latest

- name: install msgpack
  pip:
    name: msgpack
    executable: pip3

- name: install pynvim
  pip:
    name: pynvim
    executable: pip3
