---
- name: install pip3
  become: yes
  apt:
    name: python3-pip
    state: latest

- name: install pip
  become: yes
  apt:
    name: python-pip
    state: latest

- name: update pip
  become: yes
  pip:
    name: pip
    state: latest
    executable: pip3

- name: install msgpack
  pip:
    name: msgpack
    executable: pip3

- name: install pynvim
  pip:
    name: pynvim
    executable: pip3

- name: install docker-compose
  pip:
    name: docker-compose
    executable: pip3
